### ISSUE TITLE
Insensitive case

### ISSUE THREAD

**Issue by FuriouZz** [mde/filelist#6]
Is it possible to add an option for insensitive case to `include()` et `exclude()` methods ?

Currently : 
```
const FL = new FileList
FL.include('**/*.jpg', ) // Only accept .jpg
```

With insensitive case option : 
```
const FL = new FileList
FL.include('**/*.jpg', { nocase: true }) // Accept .jpg, .JPG, .Jpg, etc...```

**Comment by mde** [comment]
This is an interesting question, for two reasons:

1. Case-sensitivity is a function of the underlying operating system -- e.g., Linux is case sensitive (foo.JPG is not the same as foo.jpg), but Windows is not (foo.JPG is the same as foo.jpg).

2. FileList already accepts a RegExp for excludes. Perhaps a better approach here would be to allow RegExps to be passed for the `include` call as well, something like this:

```javascript
let list = new FileList();
list.include(/.+\.jpg$/i); 
```

Thoughts?

**Comment by FuriouZz** [comment]
Yes, a RegExp could be better than an option.
I suppose an option, because I suppose the issue coming from minimatch. Minimatch has an option for sensitive-case (https://github.com/isaacs/minimatch#nocase). But yes, a RegExp is a better idea.

**Comment by mde** [comment]
Ah, if Minimatch has a built-in option for ignoring case, that might be trivial to implement. Would you like to try putting together a PR that simply implements it by passing that option to Minimatch?

**Comment by FuriouZz** [comment]
Yes, I can try something.

**Comment by FuriouZz** [comment]
@mde Did you see my PR #7  ?

**Comment by mde** [comment]
Sorry for the delay. Very nice work on this! Merged, and will get it into a release ASAP.

**Comment by mde** [comment]
Also added you as a collaborator -- use your powers wisely. :)
